cmd/databsae: add short usage msg's and improve error for delete
* Add the missing `short` descriptions for some commands
* Remove `cobra.ExactArgs` for a better error message

Before:

```
$ psctl db delete
Error: accepts 1 arg(s), received 0
exit status 1
```

After:

```
$ psctl db delete
Error: <database_id> is missing
exit status 1
```