shell: show a more user friendly message if `mysql` client doesn't exist
This PR improves how we check for the `msyql` client and show an error:

* We introduced a new `MySQLClientPath` function that checks and returns the path of the `msyql` client. If it doesn't exist, it returns an error with a user friendly instruction on how to install the client.
* It looks like we were checking twice for the existance of the `msyql` client, we now check only once.
* We moved the `isUnderHomebrew()` function to the `cmdutil` package.  This change is not related to this functionality, but we fixed couple of issues while we're working path finding problems.

---

Examples:

Under `linux`:

```
$ pscale shell planetscale main
Error: couldn't find the 'msyql' client CLI, which is required to run this command.
To install, follow the instructions: https://dev.mysql.com/doc/mysql-shell/8.0/en/mysql-shell-install-linux-quick.html
```

Under `macOS`:

```
$ pscale shell planetscale main
Error: couldn't find the 'msyql' client CLI, which is required to run this command.
To install, follow the instructions: https://dev.mysql.com/doc/mysql-shell/8.0/en/mysql-shell-install-macos-quick.html
```

Under `macOS` and if we detect that the user is using homebrew:

```
$ pscale shell planetscale main
Error: couldn't find the 'msyql' client CLI, which is required to run this command.
To install, run: brew install mysql-client
```

closes: https://github.com/planetscale/project-big-bang/issues/323